package neuroassistant.client;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.net.*;
import java.util.*;
import org.apache.soap.rpc.*;
import org.apache.soap.encoding.SOAPMappingRegistry;
import org.apache.soap.*;
import org.apache.soap.encoding.soapenc.StringDeserializer;
import org.apache.soap.util.xml.QName;
import java.awt.event.*;





/**
 *Classe che rappresenta l'interfaccia per l'utente Medico
 * @author Abdul Rasheed Tutakhail
 */
public class Medico extends javax.swing.JFrame {

     String etastr,etniastr,sexstr,msg;
     int age;
     String newline = "\n";

     List<String> selectedSintomi = new ArrayList();
     JCheckBox[] sintomi = new JCheckBox[10];
     String[] sintom;
      


     public Medico() {
        initComponents();
            }

   /**
    * Class che viene utlizzata per gestire i checkbox di Sintomi
    */
    private class SintomiItemListener implements ItemListener {
        ArrayList selectedSintomlist;
        private SintomiItemListener(ArrayList<String> selectedSintomi) {
            this.selectedSintomlist = selectedSintomi;
        }

        @Override
        public void itemStateChanged(ItemEvent e) {
            //Aggiungi o rimuovi il testo dei Checkbox secondo
            //Stato di Selezione
            if(e.getStateChange() == ItemEvent.SELECTED){
                this.selectedSintomlist.add(((JCheckBox)e.getSource()).getText());
            }else {
                this.selectedSintomlist.remove(((JCheckBox)e.getSource()).getText());
            }
            System.out.println(selectedSintomlist);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        eta = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        maschio = new javax.swing.JRadioButton();
        femmina = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        etnia = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        agitazione = new javax.swing.JCheckBox();
        pocoEquilibro = new javax.swing.JCheckBox();
        schizofrenia = new javax.swing.JCheckBox();
        malDiTesta = new javax.swing.JCheckBox();
        convulsioni = new javax.swing.JCheckBox();
        stress = new javax.swing.JCheckBox();
        emicrania = new javax.swing.JCheckBox();
        nausea = new javax.swing.JCheckBox();
        vomito = new javax.swing.JCheckBox();
        cefalee = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        diagnosi = new javax.swing.JTextArea();
        submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cooltext558026900.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        eta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Età");

        buttonGroup1.add(maschio);
        maschio.setActionCommand("maschio");
        maschio.setText("Maschio");

        buttonGroup1.add(femmina);
        femmina.setActionCommand("femmina");
        femmina.setText("Femmina");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Etnia");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Sesso");

        etnia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Caucasico", "Sud Asiatico", "Sud-Est Asiatico", "Nero", "Altro" }));
        etnia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etniaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(eta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(etnia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101)
                .addComponent(jLabel4)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(femmina, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maschio, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(maschio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(femmina))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etnia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Sintomi");

        agitazione.setText("Agitazione");
        agitazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agitazioneActionPerformed(evt);
            }
        });

        pocoEquilibro.setText("Poco Equilibro");

        schizofrenia.setText("Schizofrenia");

        malDiTesta.setText("Mal di Testa");

        convulsioni.setText("Convulsioni");

        stress.setText("Stress");

        emicrania.setText("Emicrania");

        nausea.setText("Nausea");
        nausea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nauseaActionPerformed(evt);
            }
        });

        vomito.setText("Vomito");

        cefalee.setText("Cefalee");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pocoEquilibro)
                            .addComponent(agitazione))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(malDiTesta, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(schizofrenia, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(convulsioni)
                            .addComponent(stress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emicrania)
                            .addComponent(nausea))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vomito)
                            .addComponent(cefalee)))
                    .addComponent(jLabel5))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agitazione)
                    .addComponent(vomito)
                    .addComponent(malDiTesta)
                    .addComponent(stress)
                    .addComponent(nausea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(schizofrenia)
                        .addComponent(pocoEquilibro))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emicrania)
                        .addComponent(cefalee)
                        .addComponent(convulsioni)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        diagnosi.setColumns(20);
        diagnosi.setRows(5);
        diagnosi.setText("Risultato Diagnosi...");
        jScrollPane1.setViewportView(diagnosi);

        submit.setText("            SUBMIT");
        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/submit.png"))); // NOI18N
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(347, 347, 347))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(360, 360, 360))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(submit)))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 private void etaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etaActionPerformed

   
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:

       etastr=eta.getText();
try{
       age=java.lang.Integer.parseInt(etastr);
       age=Integer.parseInt(etastr);
       if( age<=0 || age>=110){
          JOptionPane.showMessageDialog(null, "Il valore inserito nel campo età non è giusto", "Errore", JOptionPane.ERROR_MESSAGE);
                 }

      try{
             sexstr= buttonGroup1.getSelection().getActionCommand();
             sintom=new String[selectedSintomi.size()];
             selectedSintomi.toArray(sintom);
             etniastr= etnia.getSelectedItem().toString();
    
     





                  try {
                     URL url = new URL("http://localhost:8080/soap/servlet/rpcrouter");
                     //costruzione della chiamata
                     Call chiamata = new Call();
                     chiamata.setTargetObjectURI("urn:ServerNeuro");
                     chiamata.setMethodName("medico");
                     chiamata.setEncodingStyleURI(Constants.NS_URI_SOAP_ENC);

                     SOAPMappingRegistry smr = new SOAPMappingRegistry();
                     StringDeserializer sd = new StringDeserializer ();
                     smr.mapTypes (Constants.NS_URI_SOAP_ENC, new QName ("", "return"), null, null, sd);
                     chiamata.setSOAPMappingRegistry(smr);


                                //creazione dei parametri

                      Vector parametri = new Vector();
                      parametri.addElement(new Parameter("age", int.class, age, null));
                      parametri.addElement(new Parameter("sexstr",String.class, sexstr, null));
                      parametri.addElement(new Parameter("etniastr",String.class, etniastr, null));
                      parametri.addElement(new Parameter("sintom",String[].class, sintom, null));
                      chiamata.setParams(parametri);


                                  try {
                                        Response risp = chiamata.invoke(url, "");                                       
                                        Parameter par = risp.getReturnValue();
                                        msg = (String) par.getValue();
                                              
                                              
                                        
                                  }
                                  catch (SOAPException e) {
                                        System.out.println("Errore causata da: (" + e.getFaultCode() + ") :" + e.getMessage());
                                        msg = "errore";
                                        }

                   }
                  catch (MalformedURLException ex) {
                                  System.out.println("Exception: " + ex.getMessage());
                            }

                           
                          if (msg.equals("no")) {
                                        JOptionPane.showMessageDialog(null, "Nessuna diagnosi corrispondente ai parametri introdotti è trovata!", "ATTENZIONE", JOptionPane.ERROR_MESSAGE);
                                  }
                          else if(msg.equals("error-connessione")) {
                              JOptionPane.showMessageDialog(this, "La connessione è fallita", "Errore", JOptionPane.ERROR_MESSAGE);
                            }

                          else if(msg.equals("error-query")){
                          JOptionPane.showMessageDialog(this, "Errore nella query", "Errore", JOptionPane.ERROR_MESSAGE);

                                 }

                         else{
                        System.out.println(msg);
                        diagnosi.setText("Possibili Diagnosi:" +  newline +   newline + msg);


                         }



       }
       catch(NullPointerException e){
               JOptionPane.showMessageDialog(null, "Bisogna scegliere almeno un valore per i campi sintomi e sesso  ", "Errore", JOptionPane.ERROR_MESSAGE);
                      }


    }//GEN-LAST:event_submitActionPerformed
   catch(NumberFormatException e){
               JOptionPane.showMessageDialog(null, "Solo valori numerici possono essere inseriti nel campo età e il campo non può essere lasciato vuoto ", "Errore", JOptionPane.ERROR_MESSAGE);
         

       }

    }



    

    private void etniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etniaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_etniaActionPerformed

  
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel("com.seaglasslookandfeel.SeaGlassLookAndFeel");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Medico.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(Medico.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(Medico.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Medico.class.getName()).log(Level.SEVERE, null, ex);
                }
                new Medico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox agitazione;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cefalee;
    private javax.swing.JCheckBox convulsioni;
    private javax.swing.JTextArea diagnosi;
    private javax.swing.JCheckBox emicrania;
    private javax.swing.JFormattedTextField eta;
    private javax.swing.JComboBox etnia;
    private javax.swing.JRadioButton femmina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox malDiTesta;
    private javax.swing.JRadioButton maschio;
    private javax.swing.JCheckBox nausea;
    private javax.swing.JCheckBox pocoEquilibro;
    private javax.swing.JCheckBox schizofrenia;
    private javax.swing.JCheckBox stress;
    private javax.swing.JButton submit;
    private javax.swing.JCheckBox vomito;
    // End of variables declaration//GEN-END:variables

}
